### ISSUE TITLE
Group instance has no attribute 'name'

### ISSUE THREAD

**Issue by Khalinda** [mtl/svg2mod#16]
I can't get svg2mod to work.  I put svg2mod.py in its own directory and svg.py etc in an "svg" subdirectory.  When I run svg2mod with @kasbah's "https://kaspar.h1x.com/oshwa-2.4.svg", (see svg2mod issue "Problems converting.."), I see the following:

`C:\svg2mod>svg2mod -i oshwa-2.4.svg --format pretty -p 1.0
Parsing SVG...
No handler for element {http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd}namedview
No handler for element {http://www.w3.org/2000/svg}metadata
No handler for element {http://www.w3.org/2000/svg}defs
Traceback (most recent call last):
  File "C:\svg2mod\svg2mod.py", line 1436, in <module>
    main()
  File "C:\svg2mod\svg2mod.py", line 98, in main
    exported.write()
  File "C:\svg2mod\svg2mod.py", line 721, in write
    self._prune()
  File "C:\svg2mod\svg2mod.py", line 568, in _prune
    if name == item.name:
AttributeError: Group instance has no attribute 'name'`

I know next to nothing about Python.  Does anybody have any idea what I might be doing wrong?

**Comment by kasbah** [comment]
I just tried it again and that example still works for me. What version of Python are you running?


>C:\svg2mod>svg2mod -i oshwa-2.4.svg --format pretty -p 1.0

That doesn't make sense to me, do you mean `C:\svg2mod\svg2mod.py -i oshwa-2.4.svg --format pretty -p 1.0` ?

**Comment by kasbah** [comment]
You say you are invoking `svg2mod` but you don't have an `svg2mod` executable, only and `svg2mod.py` executable, so I am a bit confused by that. 

What do you mean "set up", you should be able to just clone the repository and use that. Alternatively you can download a zip of the repo and unpack it. You svg folder doesn't look like [the one in the repo](https://github.com/mtl/svg2mod/tree/master/svg).

**Comment by Khalinda** [comment]
Thanks again Kasbah,

That was exactly my problem.  That is, when I tried running svg2mod on its own, it complained about svg.py missing, so I downloaded that package separately and I obviously botched the installation.  It would be helpful if the Readme.md file included install instructions, such as you have just provided.

Now that I have svg2mod working, I seem to have found a bug.  I'm trying to convert some text to a logo.  The conversion is almost correct, but the center of the 'O's are drooping.  I'll look into that some more, and report it separately, if it's not something that I'm doing incorrectly.

![inkscape](https://user-images.githubusercontent.com/7431977/30922557-bcb5d9ac-a366-11e7-88d2-34dee736badd.png)
![pcvnew](https://user-images.githubusercontent.com/7431977/30922569-c1511d32-a366-11e7-8577-fccfc15d2e02.png)

**Comment by kasbah** [comment]
Good stuff, the image looks a bit like svg2mod doesn't fully understand the enclosed paths. [I wrote about how to handle that on the kicad.info forum a while back](https://forum.kicad.info/t/bbc-micro-bit-like-pad-large-for-alligator-clip/4395/6). If you are still having problems with it you should open a separate issue.

**Comment by Khalinda** [comment]
Thanks once more,

I had no idea what I was doing, but I was able to follow your procedure and even simplify it somewhat, since I needed to generate "positive" text.  It worked perfectly.

**Comment by kasbah** [comment]
Do you think this OK to be closed or is there something unresolved remaining?
