### ISSUE TITLE
broken? AttributeError: 'dict' object has no attribute 'iterkeys'

### ISSUE THREAD

**Issue by greyltc** [mtl/svg2mod#29]
svg2mod -i logo.svg 
Parsing SVG...
No handler for element {http://www.w3.org/2000/svg}metadata
No handler for element {http://www.w3.org/2000/svg}defs
No handler for element {http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd}namedview
transform: scale [0.26458333]
ARC: 7.5590562, 7.5590562, 0, 0, 0, 34.771484, 1.7695312
ARC: 7.5590562, 7.5590562, 0, 0, 0, 0.75585938, 25.771484
ARC: 7.5590562, 7.5590562, 0, 0, 0, 4.5351562, 67.232422
ARC: 7.5590562, 7.5590562, 0, 0, 0, 42.330078, 84.689453
ARC: 7.5590562, 7.5590562, 0, 0, 0, 76.345703, 60.685547
ARC: 7.5590562, 7.5590562, 0, 0, 0, 72.566406, 19.224609
ARC: 7.5590562, 7.5590562, 0, 0, 0, 38.373047, 0.7578125
ARC: 0.944882, 0.944882, 0, 0, 1, 45.542969, 26.220703
ARC: 0.944882, 0.944882, 0, 0, 1, 43.654297, 30
ARC: 0.944882, 0.944882, 0, 0, 1, 44.597656, 25.275391
ARC: 0.94488199, 0.94488199, 0, 0, 1, 37.248047, 28.873047
ARC: 0.94488199, 0.94488199, 0, 0, 1, 38.585938, 32.882812
ARC: 0.94488199, 0.94488199, 0, 0, 1, 35.912109, 28.873047
ARC: 0.94488199, 0.94488199, 0, 0, 1, 36.59375, 28.597656
ARC: 0.94488193, 0.94488193, 0, 0, 1, 53.283203, 28.873047
ARC: 0.94488193, 0.94488193, 0, 0, 1, 53.283203, 30.210938
ARC: 0.94488193, 0.94488193, 0, 0, 1, 49.275391, 31.546875
ARC: 0.94488193, 0.94488193, 0, 0, 1, 52.628906, 28.597656
ARC: 4.9133857, 4.9133857, 0, 0, 1, 49.511719, 37.558594
ARC: 4.9133857, 4.9133857, 0, 0, 1, 44.597656, 42.472656
ARC: 4.9133857, 4.9133857, 0, 0, 1, 39.685547, 37.558594
ARC: 4.9133857, 4.9133857, 0, 0, 1, 44.597656, 32.646484
ARC: 0.94488198, 0.94488198, 0, 0, 1, 37.039062, 38.503906
ARC: 0.94488198, 0.94488198, 0, 0, 1, 32.314453, 37.558594
ARC: 0.94488198, 0.94488198, 0, 0, 1, 33.259766, 36.615234
ARC: 0.94488194, 0.94488194, 0, 0, 1, 52.158203, 36.615234
ARC: 0.94488194, 0.94488194, 0, 0, 1, 56.882812, 37.558594
ARC: 0.94488194, 0.94488194, 0, 0, 1, 55.9375, 38.503906
ARC: 0.94488194, 0.94488194, 0, 0, 1, 52.119141, 36.615234
ARC: 0.94488197, 0.94488197, 0, 0, 1, 39.921875, 43.572266
ARC: 0.94488197, 0.94488197, 0, 0, 1, 35.912109, 46.246094
ARC: 0.94488197, 0.94488197, 0, 0, 1, 35.912109, 44.908203
ARC: 0.94488197, 0.94488197, 0, 0, 1, 39.267578, 41.960938
ARC: 0.94488195, 0.94488195, 0, 0, 1, 49.892578, 41.960938
ARC: 0.94488195, 0.94488195, 0, 0, 1, 49.986328, 41.960938
ARC: 0.94488195, 0.94488195, 0, 0, 1, 50.611328, 42.236328
ARC: 0.94488195, 0.94488195, 0, 0, 1, 53.283203, 46.246094
ARC: 0.94488195, 0.94488195, 0, 0, 1, 51.947266, 46.246094
ARC: 0.94488195, 0.94488195, 0, 0, 1, 49.890625, 41.960938
ARC: 0.94488196, 0.94488196, 0, 0, 1, 44.626953, 44.173828
ARC: 0.94488196, 0.94488196, 0, 0, 1, 45.542969, 45.119141
ARC: 0.94488196, 0.94488196, 0, 0, 1, 44.597656, 49.84375
ARC: 0.94488196, 0.94488196, 0, 0, 1, 43.654297, 48.898438
ARC: 0.94488196, 0.94488196, 0, 0, 1, 44.625, 44.173828
ARC: 0.94488191, 0.94488191, 0, 0, 1, 30.517578, 54.462891
ARC: 0.94488191, 0.94488191, 0, 0, 1, 29.953125, 55.673828
ARC: 0.94488191, 0.94488191, 0, 0, 1, 34.675781, 56.484375
ARC: 0.94488191, 0.94488191, 0, 0, 1, 42.990234, 54.462891
ARC: 0.94488191, 0.94488191, 0, 0, 1, 42.425781, 55.673828
ARC: 0.94488191, 0.94488191, 0, 0, 1, 47.148438, 56.484375
ARC: 0.94488191, 0.94488191, 0, 0, 1, 55.462891, 54.462891
ARC: 0.94488191, 0.94488191, 0, 0, 1, 54.898438, 55.673828
ARC: 0.94488191, 0.94488191, 0, 0, 1, 58.394531, 63.638672
ARC: 0.94488191, 0.94488191, 0, 0, 1, 57.449219, 64.583984
ARC: 0.94488191, 0.94488191, 0, 0, 1, 19.654297, 62.693359
ARC: 0.94488191, 0.94488191, 0, 0, 1, 22.203125, 56.484375
ARC: 0.94488191, 0.94488191, 0, 0, 1, 29.583984, 53.841797
transform: scale [1.0, -1.0]
Traceback (most recent call last):
  File "/usr/bin/svg2mod", line 11, in <module>
    load_entry_point('svg2mod==0.1.0', 'console_scripts', 'svg2mod')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2725, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2343, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2349, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/svg2mod/svg2mod.py", line 1450, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/svg2mod/svg2mod.py", line 102, in main
    exported.write()
  File "/usr/lib/python3.7/site-packages/svg2mod/svg2mod.py", line 722, in write
    self._prune()
  File "/usr/lib/python3.7/site-packages/svg2mod/svg2mod.py", line 556, in _prune
    for name in self.layer_map.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

**Comment by urish** [comment]
See #28, it fixes this issue
