### ISSUE TITLE
Error Running svg2mod 

### ISSUE THREAD

**Issue by hhaudio** [mtl/svg2mod#39]
Hi, I downloaded svg2mod as a zip file, and when I try to running it I get the following error:

Traceback (most recent call last):
  File "svg2mod.py", line 10, in <module>
    import svg2mod.svg as svg
  File "/Users/emmettpalaima/Downloads/svg2mod-master/svg2mod/svg2mod.py", line 10, in <module>
    import svg2mod.svg as svg
ImportError: No module named svg

Any idea what's causing this and how I can fix this?

**Comment by Sodium-Hydrogen** [comment]
This repo appears to no longer be actively maintained. There is another repo that has more updates and better installation instructions. It can be found at https://github.com/svg2mod/svg2mod
